fragment GeneralFields on GeneralRecord {
  navigation {
    ...NavigationHomeItem
    ...NavigationCamperItem
    ...NavigationFaqItem
    ...NavigationAboutItem
  }
  footerNav {
    ...NavigationCookiesItem
    ...NavigationPrivacyItem
    ...NavigationTermsItem
  }
}
